### ISSUE TITLE
A nicer view

### ISSUE THREAD

**Issue by hecolivera** [altimetrik-onboarding-uy/holivera#5]
_In the user view we need a fresh, simple but clever view managed by columns, one for "New", one for "Ready", one for "In Progress" and also one for "Done"_

**Implementation notes**
given the dev experience we thin the better way to implement this is with the use of bootstrap, this will also help the user to see his app in every device available because of the responsive features that bootstrap gives.

**Comment by rjulianialtimetrik** [comment]
@hecolivera the view's columns are not bound to the work item's type, but to its status, so there should be one for "New", one for "Ready", one for "In Progress" and one for "Done".
